/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.soapinterface;

/**
 *
 * @author UNIVERSO
 */
public class telainterface extends javax.swing.JPanel {

    /**
     * Creates new form telainterface
     */
    public telainterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btaddinterface = new javax.swing.JButton();
        btaltinterface = new javax.swing.JButton();
        btexcinterface = new javax.swing.JButton();
        btconsinterface = new javax.swing.JButton();
        btlistinterface = new javax.swing.JButton();
        btlocinterface = new javax.swing.JButton();
        btsairinterface = new javax.swing.JButton();

        jLabel1.setText("Interface Soap Cliente");

        btaddinterface.setText("Adicionar");
        btaddinterface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddinterfaceActionPerformed(evt);
            }
        });

        btaltinterface.setText("Alterar");
        btaltinterface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaltinterfaceActionPerformed(evt);
            }
        });

        btexcinterface.setText("Excluir");
        btexcinterface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexcinterfaceActionPerformed(evt);
            }
        });

        btconsinterface.setText("Consultar");
        btconsinterface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btconsinterfaceActionPerformed(evt);
            }
        });

        btlistinterface.setText("Listar");
        btlistinterface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlistinterfaceActionPerformed(evt);
            }
        });

        btlocinterface.setText("Localizar");
        btlocinterface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlocinterfaceActionPerformed(evt);
            }
        });

        btsairinterface.setText("Sair");
        btsairinterface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsairinterfaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(139, 139, 139))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btaltinterface, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btaddinterface, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btexcinterface, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btconsinterface, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btlistinterface, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btlocinterface, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btsairinterface, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(122, 122, 122))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btaddinterface)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btaltinterface)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btexcinterface)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btconsinterface)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btlistinterface)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btlocinterface)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btsairinterface)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btaddinterfaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddinterfaceActionPerformed
        new telaadd().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btaddinterfaceActionPerformed

    private void btaltinterfaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaltinterfaceActionPerformed
        new telainterface().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btaltinterfaceActionPerformed

    private void btexcinterfaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexcinterfaceActionPerformed
        new telaexclui().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btexcinterfaceActionPerformed

    private void btconsinterfaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btconsinterfaceActionPerformed
        new telaconsulta().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btconsinterfaceActionPerformed

    private void btlistinterfaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlistinterfaceActionPerformed
        new telalistatipo().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btlistinterfaceActionPerformed

    private void btlocinterfaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlocinterfaceActionPerformed
        new telalocaliza().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btlocinterfaceActionPerformed

    private void btsairinterfaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsairinterfaceActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btsairinterfaceActionPerformed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telainterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telainterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telainterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telainterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new telainterface().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btaddinterface;
    private javax.swing.JButton btaltinterface;
    private javax.swing.JButton btconsinterface;
    private javax.swing.JButton btexcinterface;
    private javax.swing.JButton btlistinterface;
    private javax.swing.JButton btlocinterface;
    private javax.swing.JButton btsairinterface;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
